### ISSUE TITLE
请支持的 node_abi 48

### ISSUE THREAD

**Issue by jschyz** [weixin/node-lwip#2]
https://github.com/weixin/node-lwip/blob/master/prebuild.js#L11

现在的node 6.0.0之后的版本，NODE_MODULE_VERSION 为 48

node prebuild 的时候提示：Your node version is out of date, please install the latest one!

**Comment by eyasliu** [comment]
+1, 因为这个原因导致根本不能用

**Comment by littledu** [comment]
mark , 我周六日看看

**Comment by littledu** [comment]
node-lwip  是 lwip 的预编译，目前 lwip 尚未支持 node 6.0.0 之后的版本。静等 lwip 更新吧。

**Comment by littledu** [comment]
@Jschyz @eyasliu 

```
npm install node-lwip@latest
```

已支持 node 6.0.0 之后版本。

**Comment by brandonxiang** [comment]
我用electron什么版本才能对应上node-lwip？

我用最新版本的electron1.6.10,node6.9.2,出现版本对不上的问题。

```
'/Users/brandonxiang/github/nodemap/node_modules/node-lwip/build/Release/lwip_image.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/brandonxiang/github/nodemap/node_modules/bindings/bindings.js:76:44)
    at /Users/brandonxiang/github/nodemap/node_modules/node-lwip/lib/Image.js:3:41
```

请教用什么版本好？
